---
- hosts: localhost
  connection: local
  vars_prompt:
    - name: git_user
      private: no
    - name: git_pass
      private: yes

  roles:
    #############################################################################
    # Foundational ##############################################################
    #############################################################################

    - role: homebrew
      tags: [foundational, package-and-build, homebrew]

    # Depends on homebrew.
#    - role: git
#      tags: [foundational, brew-pkg, git]

    # Depends on homebrew.
    - role: gnu-command-line-tools
      tags: [foundational, brew-pkg, gnu-command-line-tools]
    # Depends on homebrew.
    - role: make
      tags: [foundational, package-and-build, brew-pkg, make]

# FIXME:
#    - role: cmake
#      tags: [foundational, package-and-build, bespoke-pkg, cmake]
#      vars:
#        # https://cmake.org/download/
#        cmake_version: "3.22.0"

    - role: llvm
      tags: [foundational, package-and-build, brew-pkg, llvm]

    - role: openssl
      tags: [foundational, package-and-build, brew-pkg, openssl]

    # Depends on homebrew.
    - role: bash
      tags: [foundational, brew-pkg, programming-languages, bash]

#    - role: python3
#      tags: [foundational, programming-languages, bespoke-pkg, python3]
#      vars:
#        # NOTE: update PYTHON_VERSION in Makefile when changing this.
#        # https://www.python.org/ftp/python/
#        python3_version: "3.11.2"
#        # 11 is a "Universal 2" binary which works on Apple Silicon.
#        # 10.9 does not work on Apple Silicon.
#        python3_macos_version: "11" # this is used in the .pkg file name.
#        python3_version_major_minor: "{{ python3_version | regex_replace('^([0-9]+)\\.([0-9]+)(?:\\.[0-9]+)?$', '\\1.\\2') }}"

#    - role: mac-ports
#      tags: [foundational, package-and-build, bespoke-pkg, mac-ports]
#      vars:
#        # https://www.macports.org/install.php
#        macports_version: "2.8.1"
##        macports_mac_release: "12-Monterey"
#        macports_mac_release: "10.15-Catalina"


    - role: node
      tags: [foundational, programming-languages, bespoke-pkg, node]
      vars:
        # https://nodejs.org/dist/
        # https://github.com/nodejs/node/releases
        node_version: "18.17.0"

    - role: gulp
      tags: [npm-pkg, gulp]
      vars:
        gulp_version: "4.0.2"

    - role: yarn
      tags: [npm-pkg, yarn]
      vars:
        yarn_version: "1.22.19"

# FIXME
#    - role: java
#      tags: [pkg-installer, java]

#    - role: maven
#      tags: [foundational, package-and-build, brew-pkg, maven]

#    - role: gnu-tar-catalina
#      tags: [foundational, gnu-tar-catalina]

      ############
      # My Cloud #
      ############

    - role: tailscale-mac
      tags: [vpn, macos, tailscale]

    - role: seafile-client-mac
      tags: [desktop-applications, vpn, macos, pkg-installer, seafile-client]

      ## TODO: Hazel + license
      ## TODO: config & links phi alpha...

    #############################################################################
   # Fonts #####################################################################
    #############################################################################

# casks fonts are dead
#    - role: font-hack
#      tags: [fonts, brew-cask-pkg, font-hack]

    - role: consolas
      tags: [fonts, bespoke-pkg, consolas]

    - role: font-source-code-pro
      tags: [editors, font-source-code-pro]

    - role: font-iosevka
      tags: [editors, font-iosevka]

    - role: ia-duospace-font
      tags: [fonts, ia-duospace-font]

# TODO: Dejavu, Menlo, EB Garamond

#    - role: font-eb-garamond
#      tags: [fonts, font-eb-garamond]

    ###################
    # Browser & Tools #
    ###################

    - role: google-chrome
      tags: [desktop-applications, brew-cask-pkg, google-chrome]

    - role: google-drive
      tags: [desktop-applications, brew-cask-pkg]

    - role: app-alfred
      tags: [desktop-applications, app-alfred, brew-cask-pkg]

    - role: app-keyboard-maestro
      tags: [desktop-applications, macos, brew-cask-pkg, keyboard-maestro]

    - role: better-touch-tool
      tags: [configuration, bespoke-pkg, better-touch-tool, uses-secrets]
      vars:
        # https://folivora.ai/releases
        better_touch_tool_version: "2.667" # versão licenciada não está mais no site

    - role: bitwarden-cli
      tags: [security, bitwarden-cli]

    - role: doing
      tags: [doing, gem-pkg]

#    - role: sophos-home-mac
#      tags: [macos, security, sophos-home-mac]



    ########################
    # Writing and Teaching #
    ########################

    - role: emacs-pre-built
      tags: [text-editors, bespoke-pkg, emacs-pre-built]
      vars:
        emacs_pre_built_version: "30.1"
        emacs_pre_built_patch: ""

    - role: spacemacs
      tags: [macos, spacemacs, writing]
      vars:
        spacemacs_user: "brunoc"

    - role: pandoc
      vars:
        pandoc_version: 3.6.3
      tags: [bespoke-pkg, writing, pandoc]

    # - role: texlive
    #   tags: [writing, brew-pkg, texlive]

    - role: basictex
      tags: [macos, writing, brew-pkg, basictex]

    - role: latex-packages
      tags: [writing, latex-packages]

    - role: popclip
      tags: [macos, writing, popclip, mac-tools]

    - role: marked
      tags: [macos, mac-tools, writing, marked]

    - role: word-counter
      vars:
        target_dir: /opt/local/share/word-counter-app
      tags: [writing, word-counter]

    - role: revealjs
      tags: [git-repo, teaching, revealjs]

    - role: tlg
      tags: [tlg, writing]

    - role: diogenes
      tags: [diogenes, writing]

    - role: automator-apps
      vars:
        app_list:
          - ZettelCompose - Browse
          - ZettelCompose - Handout
          - ZettelCompose to docx
          - ZettelCompose
          - ZettelComposer - com grego
      tags: [macos, writing, zettel-compose-apps]

    ################
    # My git stuff #
    ################

    - role: git-with-creds
      vars:
        repo_name: bibs
      tags: [git-pvt-repo, bibs]

    - role: git-with-creds
      vars:
        repo_name: zettel-composer
      tags: [git-pvt-repo, zettel-composer]

    - role: git-with-creds
      vars:
        repo_name: profile
      tags: [git-pvt-repo, profile-src, profile]

    - role: profile-links
      tags: [git-pvt-repo, profile-links, profile]

    - role: zettel-composer
      tags: [git-pvt-repo, zettel-composer]

    ## Devel

    - role: swi-prolog
      tags: [devel, swi-prolog]

    - role: swish
      tags: [devel, swish]
      vars:
        swish_dir: /usr/local/share/swish

    - role: asdf
      tags: [devel, beam, asdf]
      vars:
        asdf: v0.14.0

    # FIXME: requer Xcode Command Line Tools + XCode completo, instalado
    # manualmente

    - role: erlang-asdf
      tags: [devel, beam, erlang-asdf]
      vars:
        erlang: latest

    - role: elixir-asdf
      tags: [devel, beam, elixir-asdf]
      vars:
        elixir: latest

    # - role: elixir
    #   tags: [devel, beam, elixir]

    #############################################################################
    # Shell #####################################################################
    #############################################################################

    - role: babashka
      tags: [shell, bespoke-pkg, babashka]

    - role: zsh
      tags: [shell, brew-pkg, zsh]

    # - role: fish
    #   tags: [shell, brew-pkg, fish]

    # - role: fish-foreign-env
    #   tags: [shell, bespoke-pkg, fish, fish-foreign-env]

    - role: iterm
      tags: [shell, brew-cask-pkg, iterm]

    - role: tmux
      tags: [shell, brew-pkg, tmux]

    - role: tmuxinator
      tags: [shell, gem-pkg, tmux, tmuxinator]

    - role: mosh
      tags: [shell, brew-pkg, mosh]

    - role: ripgrep
      tags: [shell, brew-pkg, ripgrep]

    - role: ffmpeg
      tags: [shell, brew-pkg, ffmpeg]

    - role: aws-cli
      tags: [shell, aws-cli]


    #####################
    # Productivity Apps #
    #####################

    - role: app-airmail
      tags: [desktop-applications, macos, brew-cask-pkg, airmail]

    - role: mas
      tags: [macos, foundational, mas]

    - role: devonthink
      vars:
        - devonthink_version: "3.9.8"
      tags: [macos, desktop-applications, devonthink]

    - role: busycal
      tags: [macos, planning, busycal]

    - role: app-agenda
      tags: [macos, planning, app-agenda]

    - role: toggl-cli
      tags: [pip-pkg, planning, toggl-cli]

    - role: toggl
      tags: [desktop-applications, macos, toggl]

    - role: be-focused
      tags: [pkg-installer, planning, be-focused]

    - role: mindnode
      tags: [macos, mindnode]

    ###################
    # Microsoft Stuff #
    ###################

    - role: microsoft-365
      tags: [macos, microsoft-365]

    - role: ms-teams
      tags: [macos, ms-teams, pkg-installer]

    #################
    # Remote Access #
    #################

    - role: tunnelblick
      tags: [network, pucsp, tunnelblick]

    - role: ms-rdp
      tags: [remote, network, pucsp, macos, ms-rdp]

    - role: ovpn-pucsp
      tags: [pucsp, ovpn-pucsp]

    - role: screens
      tags: [screens, macos]

    - role: luna-display
      tags: [luna-display, macos]


