---
- name: Clone SWISH repository
  git:
    repo: https://github.com/SWI-Prolog/swish.git
    dest: /usr/local/share/swish
    update: yes
    recursive: yes

- name: Install SWISH dependencies using npm
  npm:
    path: /usr/local/share/swish
    global: yes

- name: Install SWISH dependencies with yarn
  community.general.yarn:
    path: /usr/local/share/swish

- name: make src
  command: make src
  args:
    chdir: /usr/local/share/swish

- name: Create enabled configuration path
  file:
    path: /usr/local/share/swish/config-enabled
    state: directory

- name: Configure data
  file:
    src: /usr/local/share/swish/config-available/data.pl
    dest: /usr/local/share/swish/config-enabled/data.pl
    state: link

- name: Configure allow_remote
  file:
    src: /usr/local/share/swish/config-available/allow_remote.pl
    dest: /usr/local/share/swish/config-enabled/allow_remote.pl
    state: link
