---
- name: Symlink zettel-compose.py to /usr/local/bin
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/src/zettel-composer/zettel-compose.py"
    dest: /usr/local/bin/zettel-compose.py
    state: link
    mode: '0755'
  become: true
