---
- name: Tap d12frosted/emacs-plus
  homebrew_tap:
    name: d12frosted/emacs-plus

- name: Install Emacs Plus with specified options
  homebrew:
    name: "emacs-plus@{{ emacs_version }}"
    state: present
    options: [with-debug, with-mailutils, with-imagemagick]

- name: Create an alias for Emacs in Applications
  command: >
    osascript -e 'tell application "Finder" to make alias file to posix file "/opt/homebrew/opt/emacs-plus@{{ emacs_version }}/Emacs.app" 
    at posix file "/Applications" with properties {name:"Emacs.app"}'
  become: yes

