---
- name: "Install Java {{ java_version }}"
  homebrew:
    name: "openjdk@{{ java_version }}"
    state: present

- name: "Create Java symlink"
  command: "sudo ln -sfn /opt/homebrew/opt/openjdk@{{ java_version }}/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk"
  become: true
