---
- name: Ensure font installation directory exists
  file:
    path: "{{ font_install_path }}"
    state: directory
    mode: "0755"

- name: Copy font files to the target machine
  copy:
    src: "{{ item }}"
    dest: "{{ font_install_path }}/{{ item }}"
    mode: "0644"
  loop: "{{ fonts }}"

- name: Refresh font cache (optional)
  command: atsutil databases -remove
  become: yes
  ignore_errors: yes
