---
- git:
    repo: "https://{{git_user|urlencode()}}:{{git_pass|urlencode()}}@github.com/brunocbr/{{repo_name}}"
    dest: "{{home_directory}}/src/{{repo_name}}"
    update: yes
- name: remove visibility of credentials
  command:
    cmd: git remote set-url origin https://github.com/brunocbr/{{repo_name}}.git
    chdir: "{{home_directory}}/src/{{repo_name}}"
